
/* Revising the Select Query I  (MySQL)*/
SELECT * 
FROM CITY
WHERE POPULATION > 100000 AND COUNTRYCODE = 'USA';

/* Revising the Select Query II  (ORACLE)*/
SELECT NAME 
FROM CITY
WHERE POPULATION > 120000 AND COUNTRYCODE = 'USA';


/* Select All */
SELECT * FROM CITY;


/* Select By ID  (ORACLE) */
SELECT *
FROM CITY
WHERE ID = 1661;


/* Japanese Cities' Attributes */
SELECT *
FROM CITY
WHERE COUNTRYCODE = 'JPN';


/* Japanese Cities' Names */
SELECT NAME
FROM CITY
WHERE COUNTRYCODE = 'JPN';

 